### ISSUE TITLE
插件是不是要更新了啊

### ISSUE THREAD

**Issue by ruancaipu** [amap-demo/amap-location-flutter#2]
The plugin `amap_location_flutter_plugin` requires your app to be migrated to the Android embedding v2. Follow the steps on https://flutter.dev/go/android-project-migration and re-run this command.

**Comment by ruancaipu** [comment]
执行 flutter packages get 报上面的错误 导致run不了

**Comment by snowowolf** [comment]
Because every version of amap_location_flutter_plugin from git depends on permission_handler ^4.2.0+hotfix.2 and flutter_map depends on permission_handler ^5.0.1+1, amap_location_flutter_plugin from git is forbidden.
So, because flutter_map depends on amap_location_flutter_plugin from git, version solving failed.
pub get failed (1; So, because flutter_map depends on amap_location_flutter_plugin from git, version solving failed.)

**Comment by roylly** [comment]
新版已经不再依赖flutter_map,相应的permission_handler版本也已升级到5.0.1
